### ISSUE TITLE
Possible zfs-auto-snapshot replacement - discussing disadvantages?

### ISSUE THREAD

**Issue by sandreas** [bashclub/proxmox-zfs-postinstall#14]
Hey there,

I'm not sure if you are aware of it, but with https://github.com/Corsinvest/cv4pve-autosnap there is a tool, that uses the Proxmox API to create zfs snapshots, so they should show up in the web interface.

I would like to know, if it is possible to replace `zfs-auto-snapshot` with this or provide a choice, which one to use. My experience with Proxmox is not that good, so I would like to discuss possible disadvantages and caveats.

Here is a german tutorial: https://techlr.de/proxmox-automatische-snapshots-einrichten/ 
Please note the last comment on the page:
> In der aktuellen Version (1.13 vom 04. Januar 2022) werden weitere Rechte benötigt: Datastore.Audit und Pool.Allocate. Wenn man das alles in einen Eintrag verpacken will, müssen die Rechte auch direkt für ‚/‘ vergeben werden und nicht für ‚/vms‘.

I would love to hear your opinion on this.

**Comment by cpzengel** [comment]
cv4pve-autosnap does not scale on a large numer of snapshots and is not comaptible with zfs-backup, so the decicion. snapshots of any tools have the same quality

**Comment by sandreas** [comment]
@cpzengel 
Great answer, thank you. If you are looking for inspiration for future optimizations, you could also take a look at https://tteck.github.io/Proxmox/
All scripts are available on https://github.com/tteck/Proxmox

My personal favourites are:
- Proxmox VE 7 Post Install 
- Proxmox CPU Scaling Governor 
- Proxmox Discord Dark Theme 

Maybe you can get something from these :-)
