### ISSUE TITLE
Keep Parameter wird in auto snapshot nicht korrekt eingetragen

### ISSUE THREAD

**Issue by matwun** [bashclub/proxmox-zfs-postinstall#3]
Hallo zusammen

Vielen Dank für euer Script, hat mir die vielen Einzelschritte zu einem guten Proxmox-Server nach czengel erspart.

Seither bekomme ich aber regelmässig Mails wie dieses:
/etc/cron.hourly/zfs-auto-snapshot
Error: The --keep parameter must be a positive integer.
run-parts: /etc/cron.hourly/zfs-auto-snapshot exited with return code 129

In der config ist folgendes Eingetragen (Variable, statt Wert):
exec zfs-auto-snapshot --quiet --syslog --label=hourly --keep=$SNAP_HOURLY //

Gruss und weiter so (Top Arbeit)
Matthias

**Comment by cpzengel** [comment]
Error: The --keep parameter must be a positive integer.

vor den beiden // muss ein leerzeichen sein

**Comment by thorstenspille** [comment]
Ist @LucaAust und mir gestern Abend bereits aufgefallen und habe es direkt gefixt.

**Comment by thorstenspille** [comment]
> Error: The --keep parameter must be a positive integer.
> 
> vor den beiden // muss ein leerzeichen sein

Teste ich noch einmal, das leerzeichen sollte aber nicht angerührt werden.

**Comment by matwun** [comment]
Hab's grad nochmals getestet -> funktioniert. Danke
