### ISSUE TITLE
[Frage] zfs-auto-snapshot deprecated?

### ISSUE THREAD

**Issue by udo1toni** [bashclub/proxmox-zfs-postinstall#9]
Moin,

ich bin da grade auf etwas gestoßen... 

https://ask.linuxmuster.net/t/proxmox-weg-von-zfs-auto-snapshot-hin-zu-cv4pve-autosnap-howto/7357

**Comment by cpzengel** [comment]
Das skalieret leider nicht

**Comment by udo1toni** [comment]
Schade... :)
